{ album: 
    { album_type: 'album',
      artists: [ [Object] ],
      available_markets: 
       [ 'AD',
         'AE',
         'AR',
         'AT',
         'AU',
         'BE',
         'BG',
         'BH',
         'BO',
         'BR',
         'CA',
         'CH',
         'CL',
         'CO',
         'CR',
         'CY',
         'CZ',
         'DE',
         'DK',
         'DO',
         'DZ',
         'EC',
         'EE',
         'EG',
         'ES',
         'FI',
         'FR',
         'GB',
         'GR',
         'GT',
         'HK',
         'HN',
         'HU',
         'ID',
         'IE',
         'IL',
         'IS',
         'IT',
         'JO',
         'JP',
         'KW',
         'LB',
         'LI',
         'LT',
         'LU',
         'LV',
         'MA',
         'MC',
         'MT',
         'MX',
         'MY',
         'NI',
         'NL',
         'NO',
         'NZ',
         'OM',
         'PA',
         'PE',
         'PH',
         'PL',
         'PS',
         'PT',
         'PY',
         'QA',
         'RO',
         'SA',
         'SE',
         'SG',
         'SK',
         'SV',
         'TH',
         'TN',
         'TR',
         'TW',
         'US',
         'UY',
         'VN',
         'ZA' ],
      external_urls: 
       { spotify: 'https://open.spotify.com/album/1ER3B6zev5JEAaqhnyyfbf' },
      href: 'https://api.spotify.com/v1/albums/1ER3B6zev5JEAaqhnyyfbf',
      id: '1ER3B6zev5JEAaqhnyyfbf',
      images: [ [Object], [Object], [Object] ],
      name: 'Hunting High And Low',
      release_date: '1985-06-01',
      release_date_precision: 'day',
      total_tracks: 10,
      type: 'album',
      uri: 'spotify:album:1ER3B6zev5JEAaqhnyyfbf' },
   artists: 
    [ { external_urls: [Object],
        href: 'https://api.spotify.com/v1/artists/2jzc5TC5TVFLXQlBNiIUzE',
        id: '2jzc5TC5TVFLXQlBNiIUzE',
        name: 'a-ha',
        type: 'artist',
        uri: 'spotify:artist:2jzc5TC5TVFLXQlBNiIUzE' } ],
   available_markets: 
    [ 'AD',
      'AE',
      'AR',
      'AT',
      'AU',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HU',
      'ID',
      'IE',
      'IL',
      'IS',
      'IT',
      'JO',
      'JP',
      'KW',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'SA',
      'SE',
      'SG',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VN',
      'ZA' ],
   disc_number: 1,
   duration_ms: 225280,
   explicit: false,
   external_ids: { isrc: 'USWB19901214' },
   external_urls: 
    { spotify: 'https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L' },
   href: 'https://api.spotify.com/v1/tracks/2WfaOiMkCvy7F5fcp2zZ8L',
   id: '2WfaOiMkCvy7F5fcp2zZ8L',
   is_local: false,
   name: 'Take on Me',